pub const MEMORY_IN_B: usize = 4096;
pub const NUM_REGISTERS: usize = 16;
pub const SCREEN_WIDTH: usize = 64;
pub const SCREEN_HEIGHT: usize = 32;
pub const SCREEN_SIZE: usize = SCREEN_WIDTH * SCREEN_HEIGHT;
pub const STACK_LEVELS: usize = 16;
pub const PROGRAM_MEMORY_START: usize = 0x200;
pub const EMULATION_IPS: u128 = 500;
pub const DEF_SCALE: u32 = 10;
